server:
  port: 8011
spring:
  application:
    name: order
  profiles:
    active: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
custom:
  setting:
    testname: 5555
    testpass: 44444